begin;

create table if not exists public.user_profiles (
  id uuid references auth.users on delete cascade primary key,
  tier text default 'free',
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null default 'diagnostic',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.diagnostic_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prompt_preview text,
  answer_preview text,
  image_provided boolean default false,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  address text,
  phone text,
  notes text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.user_profiles enable row level security;
alter table public.usage_events enable row level security;
alter table public.diagnostic_logs enable row level security;
alter table public.clients enable row level security;

create policy user_profiles_owner
  on public.user_profiles
  for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy usage_insert_owner
  on public.usage_events
  for insert
  with check (auth.uid() = user_id);

create policy usage_read_owner
  on public.usage_events
  for select
  using (auth.uid() = user_id);

create policy logs_owner
  on public.diagnostic_logs
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy clients_owner
  on public.clients
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists usage_events_user_created_idx
  on public.usage_events(user_id, created_at desc);

create index if not exists diagnostic_logs_user_created_idx
  on public.diagnostic_logs(user_id, created_at desc);

create index if not exists clients_user_idx
  on public.clients(user_id);

/* ── conversational follow-up ── */
create table if not exists public.chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  diagnostic_log_id bigint references public.diagnostic_logs(id) on delete set null,
  prompt_summary text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.chat_messages (
  id uuid default gen_random_uuid() primary key,
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

create policy chat_sessions_owner
  on public.chat_sessions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy chat_messages_session_owner
  on public.chat_messages for all
  using (
    session_id in (select id from public.chat_sessions where user_id = auth.uid())
  )
  with check (
    session_id in (select id from public.chat_sessions where user_id = auth.uid())
  );

create index if not exists chat_sessions_user_idx
  on public.chat_sessions(user_id, created_at desc);
create index if not exists chat_messages_session_idx
  on public.chat_messages(session_id, created_at asc);

commit;

create or replace function public.count_user_usage_30d(uid uuid)
returns integer
language sql
security definer
as $$
  select count(*)::integer
  from public.usage_events
  where user_id = uid and created_at >= timezone('utc', now()) - interval '30 days';
$$;

create or replace function public.on_auth_user_created()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.user_profiles(id, tier)
  values (new.id, 'free')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.on_auth_user_created();
