begin;

create table if not exists public.user_profiles (
  id uuid references auth.users on delete cascade primary key,
  tier text default 'free',
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null default 'diagnose',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.diagnostic_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prompt_preview text,
  answer_preview text,
  image_provided boolean default false,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  address text,
  phone text,
  notes text,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.user_profiles enable row level security;
alter table public.usage_events enable row level security;
alter table public.diagnostic_logs enable row level security;
alter table public.clients enable row level security;

create policy user_profiles_owner
  on public.user_profiles
  for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy usage_insert_owner
  on public.usage_events
  for insert
  with check (auth.uid() = user_id);

create policy usage_read_owner
  on public.usage_events
  for select
  using (auth.uid() = user_id);

create policy logs_owner
  on public.diagnostic_logs
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy clients_owner
  on public.clients
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists usage_events_user_created_idx
  on public.usage_events(user_id, created_at desc);

create index if not exists diagnostic_logs_user_created_idx
  on public.diagnostic_logs(user_id, created_at desc);

create index if not exists clients_user_idx
  on public.clients(user_id);

commit;

create or replace function public.count_user_usage_30d(uid uuid)
returns integer
language sql
security definer
as $$
  select count(*)::integer
  from public.usage_events
  where user_id = uid and created_at >= timezone('utc', now()) - interval '30 days';
$$;

create or replace function public.on_auth_user_created()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.user_profiles(id, tier)
  values (new.id, 'free')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.on_auth_user_created();
